### ISSUE TITLE
Rerun feedstock - to publish alembic 1.12.0

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/alembic-feedstock#80]
### Comment:

 alembic 1.11.3 is the latest available, the PR to merge and publish v1.12.0 seems to have failed with an error.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=773188&view=results
/.azure-pipelines/azure-pipelines-linux.yml (Line: 15, Col: 3): Unexpected value 'swapfile_size'

**Comment by xylar** [comment]
@rxm7706, thanks for noticing that.  I'm not sure what went wrong with CI but I missed that it just didn't appear to run.  We should be good now.
